services:
  - type: web
    name: starup-ecommerce
    runtime: python
    rootDir: backend
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: ADMIN_PASSWORD
        value: admin1234
